cache:
  mount:
    - node_modules
    - .git
    - public/lib

build:
  main:
    image: mhart/alpine-node:4.5
    commands:
      - apk update
      - apk add git
      - rm -r /var/cache/apk
      - npm install -g bower
      - npm install
      - bower install --config.interactive=false --allow-root
      - node_modules/.bin/gulp build
      - node_modules/.bin/gulp test
    
compose:
  mongo:
    image: newcrossfoodcoop/nxfc-mongo:latest
    
publish:
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: latest
    when:
      branch: master
      
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: $$TAG
    when:
      event: tag
