cache:
  mount:
    - node_modules
    - .git
    - public/lib

build:
  main:
    image: newcrossfoodcoop/nxfc_base:v4.6.0
    commands:
      - npm install
      - node_modules/.bin/gulp build
      - node_modules/.bin/gulp drone:test
  karma:
    image: newcrossfoodcoop/nxfc_karma:v0.1.0
    commands:
      - cd /home/karma
      - gulp karma --conf $DRONE_BUILD_DIR/karma.conf.js
    
compose:
  mongo:
    image: newcrossfoodcoop/nxfc-mongo:latest
    
publish:
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: latest
    when:
      branch: master
      
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: $$TAG
    when:
      event: tag
