cache:
  mount:
    - node_modules
    - .git
    - public/lib

build:
  main:
    image: newcrossfoodcoop/nxfc_base:v4.5.2
    commands:
      - npm install
      - node_modules/.bin/gulp build
      - node_modules/.bin/gulp drone:test
  karma:
    image: muccg/karma:latest
    commands:
      - /docker-entrypoint.sh karma /drone/src/bower.json --log-level info --browsers=Firefox --reporters=progress karma.conf.js
    
compose:
  mongo:
    image: newcrossfoodcoop/nxfc-mongo:latest
    
publish:
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: latest
    when:
      branch: master
      
  docker:
    username: bsimpson53
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: newcrossfoodcoop/nxfc
    tag: $$TAG
    when:
      event: tag
