version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "35729:35729"
      - "5858:5858"
    volumes:
      - "./modules:/home/app/modules" 
      - "./uploads:/home/app/uploads"
    depends_on:
      - mongo
      - products_api
      - ghost_api
    environment:
      - OWNER="admin"
      - MONGO_HOST=mongo
      - PRODUCTS_API_HOST=products_api
      - GHOST_API_HOST=ghost_api
      
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo"
    ports:
      - "27017:27017"
      
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
      
  ghost_api:
    image: newcrossfoodcoop/nxfc_ghost:latest
    ports:
      - "3020:3020"
    command: gulp api
      
  products_api:
    image: newcrossfoodcoop/nxfc_products:latest
    ports:
      - "3010:3010"
    depends_on:
      - mongo
      - products_worker
    environment:
      - MONGO_HOST=mongo
    command: gulp api

  products_worker:
    image: newcrossfoodcoop/nxfc_products:latest
    ports:
      - "3014:3014"
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
      - DEBUG=ingester
    command: gulp worker
