version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mongo:
    image: "newcrossfoodcoop/nxfc-mongo:latest"
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
      - "35729:35729"
      - "5858:5858"
      - "2368:2368"
    volumes:
      - "./modules:/home/app/modules" 
      - "./uploads:/home/app/uploads"
    depends_on:
      - mongo
      - products_api
    environment:
      - OWNER="admin"
      - MONGO_HOST=mongo
  products_worker:
    image: newcrossfoodcoop/nxfc_products:latest
    depends_on:
      - mongo
      - products_api
      - redis
    ports:
      - "3014:3014"
    environment:
      - MONGO_HOST=mongo
      - REDIS_HOST=redis
  products_api:
    image: newcrossfoodcoop/nxfc_products:latest
    depends_on:
      - mongo
      - products_worker
    ports:
      - "3010:3010"
    environment:
      - MONGO_HOST=mongo
