Vagrant.configure("2") do |config|

  config.vm.define "base" do |app|
    app.vm.provider "docker" do |d|
      d.build_dir = "../../"
      d.build_args = ["--file=Dockerfile"]
      d.name = "nxgfc_base"
      d.remains_running = false
    end
  end
end
